---
title: Make a musical instrument
hero_image: images/banner.png
description: Make a musical instrument with Scratch and a Raspberry Pi
meta_title: Raspberry Pi Projects | Scratch | Musical instrument 
meta_description: The fifth Raspberry Pi project in the Physical computing with Scratch path. Use your new skills to make a musical instrument. 
version: 4
listed: true
copyedit: true
last_tested: '2021-03-23'
steps:
  - title: You will make
  - title: Make your instrument
  - title: Connect and code your instrument
    completion:
      - engaged
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: What next?
