---
title: Make a musical instrument
hero_image: images/banner.png
description: Make a musical instrument with Scratch and a Raspberry Pi
version: 4
listed: true
copyedit: true
last_tested: '2021-03-23'
steps:
- title: Introduction
- title: Make your instrument
- title: Connect and code your instrument
  completion:
  - engaged
  - internal
- title: Reflect
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
  - external
- title: Upgrade your project
- title: What next?
