title: scratchpc-musical-instrument
hero_image: images/banner.png
description: scratchpc-musical-instrument description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Introduction
  - title: Make your instrument
  - title: Connect and Code your instrument
  - title: What next?
