title: Make a musical instrument
hero_image: images/banner.png
description: scratchpc-musical-instrument description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Introduction
  - title: Make your instrument
  - title: Connect and code your instrument
  - title: Reflect
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: What next?
